### ISSUE TITLE
downloadable csv file

### ISSUE THREAD

**Issue by berlintam** [rubycorns/whatdojuniorsgetpaid#10]
It would be great if people could download a file of our information, which they could then use for whatever they want!

**Comment by TPei** [comment]
Heyho, I could do that. Can't assign myself unfortunately, but just see me as on it :D

**Comment by TPei** [comment]
Ok, added appropriate methods to the model. For now I'll just add a "download to csv" button to the top of the overview page. Can always move that somewhere else later on...

**Comment by TPei** [comment]
See PR #14

**Comment by berlintam** [comment]
closed with #14
