### ISSUE TITLE
After taxes / before taxes

### ISSUE THREAD

**Issue by TPei** [rubycorns/whatdojuniorsgetpaid#12]
When filling in the form the box says "I make about this much per year before taxes", but in the overview section the text says "salary is _ € per year after taxes"
So we should either change `views/junior_stories/new.html.erb#39` or `models/junior_story.rb#101`
I'll open a PR changing the model, I guess before taxes is more interesting, tax deduction is potentially too individual and can always be done manually...

**Comment by TPei** [comment]
See: PR #13

**Comment by berlintam** [comment]
closed with https://github.com/rubycorns/whatdojuniorsgetpaid/pull/13
