### ISSUE TITLE
Make primary technology a dropdown

### ISSUE THREAD

**Issue by PragTob** [rubycorns/whatdojuniorsgetpaid#3]
I feel the field is critical to the data analysis so it shouldn't be riddled with unclean custom user input. So primary technology should really be a dropdown with the most common technologies and then maybe a field with a text description for other.

**Comment by berlintam** [comment]
done https://github.com/rubycorns/whatdojuniorsgetpaid/commit/80077988a4e43aecddda027cbfdb7eccdfe446d4
