### ISSUE TITLE
Make sure that City is properly sanitized

### ISSUE THREAD

**Issue by PragTob** [rubycorns/whatdojuniorsgetpaid#5]
It's sort of hard to make a dropdown for all cities over the word (although that would be desirably), failing at that it'd be important to make sure it is sanitized, white space removed, same capitalization etc. :)

**Comment by berlintam** [comment]
done https://github.com/rubycorns/whatdojuniorsgetpaid/commit/4143fd15f57f4ea94bc059e35024d741a7b0e428
