### ISSUE TITLE
Make a differentiation between freelancer and employed

### ISSUE THREAD

**Issue by PragTob** [rubycorns/whatdojuniorsgetpaid#6]
Freelancers usually make much more before taxes, thereby skewing the outcomes in a different direction. Therefore it's rather important imo to make that differentiation for a good analysis.

**Comment by berlintam** [comment]
done https://github.com/rubycorns/whatdojuniorsgetpaid/commit/7b153b1ac89f93efcb19b1fa579f676ac59aa28b
