### ISSUE TITLE
Get a more accurate input for days worked

### ISSUE THREAD

**Issue by PragTob** [rubycorns/whatdojuniorsgetpaid#7]
full time/part time can be quite different, i.e. what's up with 4days/week. Is that full time or part time? 

So n days/per week or m hours per week sounds good. 

Later on, for fancy graphs, the data could be aggregated again if desired.

**Comment by berlintam** [comment]
done https://github.com/rubycorns/whatdojuniorsgetpaid/commit/7b153b1ac89f93efcb19b1fa579f676ac59aa28b
